apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      limits:
      - default:
          cpu: "500m"
          memory: "512Mi"
        defaultRequest:
          cpu: "250m"
          memory: "768Mi"
        type: Container
      containers:
        - name: wiz-technical-assessment
          image: 017820672665.dkr.ecr.us-east-2.amazonaws.com/wiz-technical-assessment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080