apiVersion: apps/v1
kind: Deployment
metadata:
  name: WizTechnicalAssessment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: WizTechnicalAssessment
          image: 017820672665.dkr.ecr.us-east-2.amazonaws.com/wiz-technical-assessment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080