apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: wiz-technical-assessment
          image: 017820672665.dkr.ecr.us-east-2.amazonaws.com/wiz-technical-assessment:latest
          resources:
            - requests:
                cpu: "250m"
                memory: "512Mi"
              limits:
                cpu: "5000m"
                memory: "768Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080