apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky-webserver
        image: 017820672665.dkr.ecr.us-east-2.amazonaws.com/wiz-technical-assessment:latest
        resources:
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: MONGODB_HOST
            value: ec2-18-227-107-220.us-east-2.compute.amazonaws.com
          - name: MONGODB_PORT
            value: "27017" #MongoDB default port
          - name: MONGODB_DB       
            value: "myapp" 
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          - name: MONGODB_PASS
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password 
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: SECRET_KEY
          - name: MONGODB_URI
            value: 'mongodb://$(MONGODB_USER):$(MONGODB_PASS)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DB)?authSource=admin'