apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # username: bXlhcHB1c2Vy
  username: YWRtaW5Vc2Vy
  # password: bXBhcHBwd2Q=
  password: d3dQenF6bURpUjJO
  SECRET_KEY: c2VjcmV0MTIz