apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
spec:
  selector:
    app: tasky
  type: ExternalName
  #externalName: ec2-18-227-107-220.us-east-2.compute.amazonaws.com
  externalName: 172.31.49.50