apiVersion: v1
kind: Pod
metadata:
  name: Pod-Update
  namespace: default
spec:
  containers:
    env:
    - name: MONGODB_HOST
        value: "172.31.49.50"
      name: MONGODB_PORT
        value: "27017"
      name: MONGODB_DB
        value: "myapp"
      name: MONGODB_USER
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: username
      name: MONGODB_PASS
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: password
      name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: SECRET_KEY      
      name: MONGODB_URI
        value: "MONGODB_URI="mongodb://$(MONGODB_USER):$(MONGODB_PASS)@$(MONGODB_HOST):$(MONGODB_PORT)"